### ISSUE TITLE
win32/64 bin?

### ISSUE THREAD

**Issue by zer0c0nf** [gjedeer/tuntox#11]
Is it possible to make a porting code so that it works on windows ?

Thank you .

**Comment by gjedeer** [comment]
It's probably possible to compile this code with mingw or cygwin.
I have no plans to port it to winapi, it's a hobby project.

**Comment by dimzon** [comment]
Can anybody compile it with minigw please? Simple win32 build is enough will work fine on both 32/64 bit platforms.

**Comment by gjedeer** [comment]
So I played with Windows today. What a pile of steaming crap, I wonder how people get anything compiled on this platform.

Anyway: I failed with mingw - it seems it doesn't support the BSD socket API, and has a lot of conflicts in its include files.

0.0.5 version built with Cygwin: https://f.gdr.name/tuntox.exe (Github doesn't allow exe files)

Any Windows-related issues will be closed unless accompanied with a patch.
