### ISSUE TITLE
Why no option to allow particular addresses keys?

### ISSUE THREAD

**Issue by o-jasper** [gjedeer/tuntox#14]
Seems like a fairly obvious thing to do?

Wouldnt this control access equally well, assuming the password is always provided when the address is used. If you use the address much more than you use it for tuntox, a compromised machine will have to wait until you provide the password.(aswel)

**Comment by gjedeer** [comment]
Only because I don't use it this way, it will be an easy addition (next time I have time to work on it)

**Comment by gjedeer** [comment]
Check out the new feature https://github.com/gjedeer/tuntox/commit/e9393fb439f94461fdc665eb85af54f156e5be75
