### ISSUE TITLE
Allow to obtain shared secret from environment variable or key file

### ISSUE THREAD

**Issue by abbat** [gjedeer/tuntox#20]
Now shared secret passed as `-s` option is visible to all through `ps` command for example. Seems it will be more secure to pass shared key as environment variable (or key file).

**Comment by gjedeer** [comment]
Thanks for your PR. It's a reasonable idea but I think a fixed variable name like TUNTOX_SHARED_SECRET is better, if you open another PR with that, I'll merge it.

Rationale: all the other UNIX programs do it this way -> principle of least surprise.

**Comment by gjedeer** [comment]
@abbat FYI, it will be included in the next release
