### ISSUE TITLE
Second connection issue

### ISSUE THREAD

**Issue by milisarge** [gjedeer/tuntox#25]
i am using tuntox,at first connection is ok but when i want to refresh to connect second attempt,it doesnt response and it needs to restart by client side

**Comment by milisarge** [comment]
to more clear:i opened my 127.0.0.1:8001 it is tunnel from x.x.x.x:8000.first i can opened it,but when i refresh the page it is spinning forever

**Comment by gjedeer** [comment]
Command line parameters, version and debug output please.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by milisarge** [comment]
client log : http://www.sudrap.org/paste/text/877955/
server log : http://www.sudrap.org/paste/text/877956/

**Comment by gjedeer** [comment]
I only just noticed. You're using an old build, and a few days before your bug report I released 0.0.5 which fixes the kind of errors you've had.

Please retry with the latest [0.0.6](https://github.com/gjedeer/tuntox/releases/tag/0.0.6) and reopen if it's still happening. Sorry for the late answer, I was trying to reproduce that without success.

**Comment by milisarge** [comment]
ok lemme try

23 Temmuz 2016 Cumartesi tarihinde, GDR! <notifications@github.com> yazdı:
