### ISSUE TITLE
Switch to c-toxcore

### ISSUE THREAD

**Issue by NicoHood** [gjedeer/tuntox#28]
Hi,
will this project switch to c-toxcore as it is the new upstream toxcore source now? Every other tox client switches to c-toxcore over time now and it would be essential for you to do so too if people want to use tuntox in their linux distribution.

Also some website links are offline:
https://git.moe/gdr/tuntox
http://tuntox.pl/

**Comment by gjedeer** [comment]
There's work underway https://github.com/gjedeer/tuntox/tree/toktok-core

Currently waiting for a fix in upstream: https://github.com/TokTok/c-toxcore/pull/305

Where did you find tuntox.pl? It was a temporary gimmick domain, all references should be removed by now. Not sure wtf is going on with git.moe at the moment, I should probably self host a repo.

**Comment by NicoHood** [comment]
It is listed here: https://www.archlinux.org/packages/community/x86_64/tuntox/

The PR you linked got already merged.

**Comment by gjedeer** [comment]
I had nothing to do with the archlinux package, I don't even know the maintainer. Contact them about it.

Expect a new Tuntox version soon.

**Comment by NicoHood** [comment]
Sure I will. just wanted to ask about the domain and project status. Thanks :)

**Comment by NicoHood** [comment]
Any news about the next release of tuntox? ArchLinux wants to upgrade their packages to c-toxcore and every other tox client already did so. I am asking because if it takes longer, we temporary drop tuntox from our packages.

**Comment by gjedeer** [comment]
Then please drop it, it's a hobby project and I'm not going to commit myself to any kind of schedule.
