### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [gjedeer/tuntox#29]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [x] [Create and/or use a 4096-bit RSA keypair](https://github.com/NicoHood/NicoHood.github.io/wiki/How-to-sign-sources-with-GPG-in-under-5-minutes) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [x] Upload the public key to a key server
* [x] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [x] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [ ] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information:**
* https://github.com/NicoHood/NicoHood.github.io/wiki/How-to-sign-sources-with-GPG-in-under-5-minutes
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by gjedeer** [comment]
Hi, please state wich points specifically I'm not doing with Tuntox. Otherwise I'm closing this issue, it's clearly some kind of copy/paste template.

On December 18, 2016 10:57:18 AM CET, Nico <notifications@github.com> wrote:
>As we all know, today more than ever before, it is crucial to be able
>to trust our computing environments. One of the main difficulties that
>package maintainers of Linux distributions face, is the difficulty to
>verify the authenticity and the integrity of the source code.
>
>The Arch Linux team would appreciate it if you would provide us GPG
>signatures in order to verify easily and quickly of your source code
>releases.
>
>**Overview of the required tasks:**
>* [ ] [Create and/or use a 4096-bit RSA
>keypair](https://github.com/NicoHood/NicoHood.github.io/wiki/How-to-sign-sources-with-GPG-in-under-5-minutes)
>for the file signing
>* The key may be used for [email
>encryption](https://www.enigmail.net/index.php/en/) too
>* Keep your key secret, use a strong unique passphrase for the key
>* [ ] Upload the public key to a key server
>* [ ] [Sign every new commit by
>default](https://help.github.com/articles/signing-commits-using-gpg/)
>* [ ] [Sign new
>tags](https://help.github.com/articles/signing-tags-using-gpg/)
>* Verify the Github Release tarball download against your local source
>* [ ] [Sign Github Release
>tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)
>
>**Additional Information:**
>*
>https://github.com/NicoHood/NicoHood.github.io/wiki/How-to-sign-sources-with-GPG-in-under-5-minutes
>* https://help.github.com/categories/gpg/
>* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
>* https://www.qubes-os.org/doc/verifying-signatures/
>*
>https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
>
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/tuntox/issues/29

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NicoHood** [comment]
Can you please sign the github .tar.gz file? You should still verify it against your local git.

I've wrapped those steps in a script. Its not yet fully finished and does not exactly do what you need, but it shows you how you can compare the github download against your local source:
https://github.com/NicoHood/gpgithub#gpgtag

**Comment by gjedeer** [comment]
0.0.6 is signed.

**Comment by NicoHood** [comment]
Thanks!
