### ISSUE TITLE
Tunnel to VNC

### ISSUE THREAD

**Issue by dcapeletti** [gjedeer/tuntox#32]
Hello,
Is it possible with tuntox to create a tunnel for VNC or perhaps for mysql? 
Thanks.

**Comment by gjedeer** [comment]
Of course. For VNC, on the VNC server you run:

./tuntox

On the client you run

./tuntox -L 5900:localhost:5900 -i (server toxid)

Assuming that your VNC is listening on port 5900 - that's the default. Then on the client you just connect to "localhost".

**Comment by dcapeletti** [comment]
Excellent. Thanks

**Comment by dcapeletti** [comment]
Just to document, for mysql is the same.
To connect with the mysql client to the server, use the following command:
mysql -u user -password --host=127.0.0.1 --port=3306

Assuming you have created the connection as follows:
./tuntox-x86 -i ToxId -L 3306:127.0.0.1:3306
