### ISSUE TITLE
closed 22 and 222 ports on the host

### ISSUE THREAD

**Issue by OrionRandD** [gjedeer/tuntox#34]
What if ports 22 and 2222 are closed on the server? Like it is with mine? I tried to connect with the right server port, but it failed. Could you give more examples or make a  youtube video or other ways to explain the the appl better? Also think about a GUI for the appl. Thx...

**Comment by gjedeer** [comment]
Then use your SSH port if it's other than 22. Just replace 22 with the port number you're using. You can check your SSH port with this command (run it on your server): `netstat -ptan | grep LISTEN | grep ssh`

**Comment by OrionRandD** [comment]
thx...
