### ISSUE TITLE
Make tuntox faster with the new tox_loop API

### ISSUE THREAD

**Issue by gjedeer** [gjedeer/tuntox#41]
https://github.com/gjedeer/tuntox/pull/40#issuecomment-294803379

https://github.com/TokTok/c-toxcore/pull/131

https://github.com/TokTok/c-toxcore/pull/335

**Comment by gjedeer** [comment]
https://gist.github.com/ValdikSS/3c953e2e40761727288f2437b165536c

**Comment by ljgdasfhk** [comment]
Is it implemented ?

**Comment by gjedeer** [comment]
Nope, busy 18 months.

**Comment by gjedeer** [comment]
I've finally found some time to implement it, just to find that the tox_loop feature has been removed:

https://github.com/TokTok/c-toxcore/pull/538

That's unfortunate as it could be a significant speed up.
