### ISSUE TITLE
Two minor bugs

### ISSUE THREAD

**Issue by FiftyPM** [gjedeer/tuntox#42]
1. util.c to_hex
a = '\0';  <<<  should be ***a = '\0'**;
2. main.c send_tunnel_request_packet 
data = calloc(1, packet_length);  <<< should be **packet_length + 1**
or later instead of strcpy use memcpy:
**memcpy**((char *)data+PROTOCOL_BUFFER_OFFSET, remote_host, strlen(remote_host));

**Comment by gjedeer** [comment]
Thanks for reviewing the code!
