### ISSUE TITLE
Your build instructions don't have a complete list of requisite libraries

### ISSUE THREAD

**Issue by ghost** [gjedeer/tuntox#43]
I've only gotten this far through guesswork.

I had to symlink `/usr/lib/pkgconfig/libtoxcore.pc` to `/usr/lib/pkgconfig/toxcore.pc` to get it to even compile, which makes me think the name is probably out of date or something? Don't know the history of that. I am using the TokTok/c-toxcore fork.

Then I got more errors, and based on them guessed I needed `libevent-dev` (from Ubuntu 16.04 packages), which turned out to be right.

Now I am getting these errors during compiling, which are extra strange. Maybe I'm using the wrong version of libsodium. I have libsodium-dev installed from the official Ubuntu repos. I can't be sure if that's the problem, because **your build instructions don't have a complete list of requisite libraries.**

These are the errors I'm stuck on: https://gist.github.com/avrildev/640c6df779ba4fec241601e31142f7e9

Can someone please help? Thanks!

**Comment by gjedeer** [comment]
It looks like toxcore has changed a lot since the last build I made. Please try an earlier release like 0.17 or 0.16: https://github.com/TokTok/c-toxcore/releases

**Comment by gjedeer** [comment]
Though the errors you're getting are from missing libsodium. Are you sure you followed toxcore installation instructions fully? https://github.com/TokTok/c-toxcore/blob/master/INSTALL.md#build-manually

**Comment by avrildev** [comment]
Yes. I have lots of experience installing c-toxcore, and both my `qtox` and `toxic` installs have no trouble using my setup. I will redo the setup of c-toxcore so I can give you an exact list of what I did later.

**Comment by gjedeer** [comment]
Interesting.... tuntox has no external dependencies other than c-toxcore. Yeah hit me up with that so i can try replicating the issue

**Comment by readyblue** [comment]
I have successfully compile this cool project on many different systems and platforms and I would like to share the list of required libraries. You will need:

- **c-toxcore** , also as @ghost pointed out, make link or copy "libtoxcore.pc" to "toxcore.pc".
It may be located on "/usr/lib/pkgconfig" or "/usr/local/lib/pkgconfig" or similar.

- **python2** (and using its package system "pip", install: )
`pip2 install Jinja2`
`pip2 install requests`

- **libevent-dev** (it must contain also "libevent_pthreads", if it does not, you need to compile "libevent" project from source)

if command `make` still does not work after this, try to use `make tuntox_nostatic`
Also use `make clean` if make hits the error(s) before next try.

PS.: on Android you will also need to add "`-llog`" to Makefile

**Comment by gjedeer** [comment]
@readyblue do you want to turn it into a PR? It compiles fine on Ubuntu 16.04 with the given dependencies. If you could turn your experience  into setup guides for the distributions which had  different needs, that would be so awesome.

Interesting about Android too, I compiled tuntox statically on Raspbian and the binary worked on Android without further dependencies. You were using the NDK, I guess? Would be nice to have a readme for Android NDK too.

On September 13, 2017 1:06:13 PM GMT+02:00, readyblue <notifications@github.com> wrote:
>I have successfully compile this cool project on many different systems
>and platforms and I would like to share the list of required libraries.
>You will need:
>
>- **c-toxcore** , also as @ghost pointed out, make link or copy
>"libtoxcore.pc" to "toxcore.pc".
>It may be located on "/usr/lib/pkgconfig" or "/usr/local/lib/pkgconfig"
>or similar.
>
>- **python2** (and using its package system "pip", install: )
>`pip2 install Jinja2`
>`pip2 install requests`
>
>- **libevent-dev** (it must contain also "libevent_pthreads", if it
>does not, you need to compile "libevent" project from source)
>
>if command `make` still does not work after this, try to use `make
>tuntox_nostatic`
>Also use `make clean` if make hits the error(s) before next try.
>
>PS.: on Android you will also need to add "`-llog`" to Makefile
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gjedeer/tuntox/issues/43#issuecomment-329134522

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by readyblue** [comment]
@gjedeer I have only stumble on this issue, because I also had trouble compiling it. And once I done in, share it. I do not care about PR.

@gjedeer No, not everyone using Ubuntu and No, not everyone is interesting using Ubuntu.

@gjedeer There is no list of dependencies in the README.md nor BUILD.md to be fair and there is no direct way to tell what is missing (no ./configure script either)

@gjedeer I spend hours to get it compiled and linked, not and easy task, so I only want to make it easier for someone else in the future, that is my "PR". If I had the information from my previous post earlier, I can save few hours of work, hope it helps someone.

@gjedeer You may not have the trouble compile and linking it, because you program it, you know it from bottom to the top, but others does not. And as you can see, there are few of us, that are facing difficulties compile and linking it. If you try to take it from their point of view, you may see it is not an easy task to compile it.

**Comment by gjedeer** [comment]
Okay, if you don't want to contribute, don't. No need to attack me.

Tuntox only depends on libtoxcore and builds with a simple `make` on
debian-derived systems. If someone else wants to create READMEs or
Makefile targets for other systems, contributions are welcome.

**Comment by gjedeer** [comment]
Closing this issue, BUILD.md should be more clear now about the dependencies.
