### ISSUE TITLE
Option to detect failures

### ISSUE THREAD

**Issue by ghost** [gjedeer/tuntox#49]
Sometimes when leaving the process running and the server disconnects or crashes, the client continues to send packages to the already dead server and never tries to reconnect even if the server is back online.
Is there a way of detecting when the server disconnected so the client can be restarted? Or a way that makes the client recreate the tunnel automatically?
And on a different context, is there a way of setting a timeout or retry count? When connecting with bad secret, the client keeps trying infinitely, and sometimes it would be a good behaviour to fail after some retries or even a timeout.

**Comment by gjedeer** [comment]
Idea for implementation: check `tox_friend_get_connection_status` periodically.

A full implementation would probably send a ping packet every now and then too, but that would be a good start. Also: this would have a nice side effect of being able to print changes in TCP/UDP mode of friend connection.

**Comment by gjedeer** [comment]
Regarding the other part of the question: I can see how it can be useful it some scenarios (scripting) to limit the number of retries.

**Comment by gjedeer** [comment]
Testing is welcome.

https://github.com/gjedeer/tuntox/commit/03d83602d3a328d89b806e23c35644ec3908dc1f
https://github.com/gjedeer/tuntox/commit/121acd73ddba12659713f27abef7524b9a0c6a48\

**Comment by gjedeer** [comment]
There's still no retry count implemented

**Comment by gjedeer** [comment]
Closing - this code has been in the main release for a long time now
