### ISSUE TITLE
Tuntox has connection speed problems

### ISSUE THREAD

**Issue by dcapeletti** [gjedeer/tuntox#51]
A partner who has developed a package called "Asistec" (Technical Support) for the [EterTICs GNU Linux](https://gnuetertics.org/) distribution uses tuntox to provide remote support via vnc to its customers.
A few days ago he told me that he noticed a slowdown of tuntox using version 0.0.8. He told me that in previous versions it worked faster and that he has noticed this change.
He told me that his connection is as follow:

> 
> Testing download speed................................................................................
> Download: 4.83 Mbit/s
> Testing upload speed................................................................................................
> Upload: 0.80 Mbit/s

He also told me that his client's connection speed is very similar and that the VNC server configuration is as follows:

> x11vnc -display :0 -ncache 10 -forever -usepw -rfbport 5900 -bg -8to24

I just wanted to send this news to get more information about the situation. Maybe my friend can get help determining how tuntox can work best.

Thank you very much

**Comment by gjedeer** [comment]
Woah, cool stuff that you're doing there!

I too am getting random speeds, sometimes the connection is direct and sometimes it's going via a TCP relay even when direct connection is possible. It's Toxcore that's selecting the routes and I don't have a way to control it as a program using that library. I tried fixing that in toxcore but the code is just unreadable.

So on a more practical note: the git master of tuntox builds with toxcore-0.2.0. My experience is that it's doing better when connecting. Try building that or I can send you a binary to test if you just want to quickly check if it's working better.

**Comment by gjedeer** [comment]
The toxcore issues don't get any attention:
https://github.com/TokTok/c-toxcore/issues/236
https://github.com/TokTok/c-toxcore/issues/195

There was also a pull request making things better on that front and after 1.5 years they finally merged it into 0.2.0 https://github.com/TokTok/c-toxcore/pull/226

**Comment by dcapeletti** [comment]
Thanks for the answer. I understand now a little more about the problem.
If you can send me a compiled binary, I would be very grateful if we could try it out more quickly.
Thank you

**Comment by gjedeer** [comment]
Let me know if it's better https://f.gdr.name/tuntox-0.0.8-c-toxcore-0.2.0

**Comment by dcapeletti** [comment]
Thank you very much. Yeah, sure, when we have several tests done, I'll write around here.

**Comment by gjedeer** [comment]
Feel free to reopen if there's a problem again
