### ISSUE TITLE
-f option is not documented

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [gjedeer/tuntox#56]
It would be great if there would be a switch for the server to whitelist allowed ports, like

tuntox -s 123456 -w 22

to only forward ssh port.

**Comment by gjedeer** [comment]
There's the `-f` option introduced by this pull request 

https://github.com/gjedeer/tuntox/pull/26

Noone bothered to document it but the filter file goes like this:
```
1.2.3.4:22
127.0.0.1:80
```
etc.

If you need to whitelist *:22, it's not possible at the moment but PR welcome.
