### ISSUE TITLE
Manually supply bootstrap nodes

### ISSUE THREAD

**Issue by gjedeer** [gjedeer/tuntox#65]
```
tuntox -b 94750E94013586CCD989233A621747E2646F08F31102339452CADCF6DC2A760A@46.146.229.184:33445
tuntox -b 28DB44A3CEEE69146469855DFFE5F54DA567F5D65E03EFB1D38BBAEFF2553255@[2605:6400:10:caa:1:be:a:7001]:33445
```

**Comment by gjedeer** [comment]
Thank you. Have you tested it with a static build? It will not work -
that's OK - but have you tested that 1) it does not crash and 2) it
does not slow down startup too much?

**Comment by froloffw7** [comment]
Static build never worked for me.. It always crashed at some place. Dynamic works fine.

**Comment by gjedeer** [comment]
Then I can't merge it, the static build is primary target of tuntox,
I don't even test dynamic, it was introduced by some distro maintainer.

Though when I have more time I'll take a look if I can make your patch
work in a static build without crashing.

**Comment by froloffw7** [comment]
Sorry, the static build with unmodified sources I mean the original code from your git without any changes.

**Comment by gjedeer** [comment]
It's merged - so I'm closing this issue. Thanks for your contribution.
