### ISSUE TITLE
Consider stdout as (default?) output option

### ISSUE THREAD

**Issue by willcohen** [gjedeer/tuntox#68]
Right now, while the choices are stderr and syslog, it might be worth having output default to stdout, or at least have it be an option. When packaging tuntox for nix, (https://github.com/NixOS/nixpkgs/pull/160548), lack of stdout has made it more difficult to quickly check for a working build.

Even if it's decided to keep default behavior as is, having a version check, likely with `--version` or `-v`, should default to stdout.

**Comment by gjedeer** [comment]
Thanks. The reasoning behind using stderr is mostly because -W option:

```
    -W <remotehostname>:<remoteport> - forward <remotehostname>:<remoteport> to
                                       stdin/stdout (SSH ProxyCommand mode)
```

But for --version, --help etc you're right, it should to stdout, I just checked how the standard GNU utilities do it and they print such output to stdout.

Also, there's no --version / --v, that needs to be implemented.

**Comment by gjedeer** [comment]
Alright:

```
$ ./tuntox -V     
Tuntox built from git commit 0ba3dc62293ece11400673965b89a99d91d7e8ed, toxcore version 0.2.13
$ 
```

--help now prints to stdout, too. Thank you for letting me know about this problem and feel free to open issues/PRs on problems with packaging.
